server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/EasyBuy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root    # root
    password: 1234    # Mizore006402.

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

jwt:
  secret-key-str: huHAQ21P5fsGgpnHKipREwz4zgwUxJ8bGl+gmW4mbl4=
  # token 有效期 单位：天
  ttl: 99

mybatis:
  mapper-locations: classpath:mapper/*.xml

alipay:
  appId: 9021000136610564
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCDSg65lV141yFwLly6JrQnQWRCYKCKbj/0Lxh/NiVZgOiYuYHOQybrpXsiGg2T0pUD6AklfAhdYupU6QvV3ptpExlNARYcHnHOjN62pNrkU4R/fvDVTM9W60tciYrUGWDXzR6gGC9CrtgqOJhOTD1ciTim7pfdcQ1v3MxH2iCGOviUqFwOy7U4cCEc56rR+1KaPjDzcPX1uxYpIIjBVmdylR+4uAxH6/MGXtckGf14CQPFmzcPLHSeWkBOwPeNmeFSH8O8fTHwJlzXaHdOd53nYY7l/4fvwTB0qA6bcgkeyMwiBf4XB8+0CmVgfMCvwsCADUVir1fRn5g+f7IPHAClAgMBAAECggEAU5TADxGx8g4zMXGygqfFJQCSTVeqnLZXbKLW25Wi7XoNmbzvkFpb2sT8wNcJMcRsLZJ40C5IPPuN5wR+DmerVJdeEhHQ+5G+LhqsZmZJG/a3cVtlAsXlcZZV4dGGWkTVzEy/ZHhBDhi1cRuaiq4qmlCZilx2vfkM7twICO4qqojRIcUhU1CoNeMOw1tsjKoy/f4nMvzO4INmQIOJchk8McNGD61/RM5m41qrK41bIqZ/XWIhY10QycXE5WebfaZNI9bqv7xQ+xbqNv3h5FvSwgQbvC7zdj/agdy+6bhp0FAiPYikeb3wFOuaTyY7SK4reprMGI9+Vomq5w9mF6Gm+QKBgQDPkFJg0edoimzamAmRToqq7fbhifjzFYFAkcT/v3mrMbYlqUt3bRd0JsaM2EAcBMUdVrWMmhDYk2Du5OILAB+Ae8GFMwlRT2GxOFOQY9CthJf3XhkF/X6SOs0ghCyUEDMAFGQY9PLHSAZFX4LpQTioq2aPZG3hz//zcN0RL9xu0wKBgQCh7SpP3FzY7gB/gZom3VA8OIM2nbvjCPQ5e8KB3gybANQIEZYwYm808z6eH3kwDOvmT6sy33B6zlLfcGVw4gsq0QRvtKR7NL23c7A1D7O+ap+vggroW80TNsFKKaJIhLzH6E8JVRGMfzxMHbA7ssLcayl2LAgcGoj+XrWhVQJXpwKBgA5DxOWSh2zP1ptPR5kM5MrKf+UQLmPGXpOpcPiCmEIDsJj2AZG7lZkN8SdM1VsXmNRjWSbIj8/SkR7Z7A8FeyTBXJNi5okIA5bCYDvUIEtMiYUemmmm+kPidqZ9bvLeCiM/Q4HTk7vOX1/1KHIPYW12Gh5QsJyMRvLcFtVPjL6xAoGASx28HSP6pl9yN7QlkJXmHKmSpQlzGZUTxn7U8m3Rpy4xLjUKWROwxv14NN4g19uGq2aV4pmoki+YXjLDvCQATjJ8Pl2sV8NVpv6x5UuNdG39+er3qGa9sYYbEI5TzBRXht0LnSarZ2O20xCKqob4wkusBjfS40aj+mxxEZBf780CgYA8Sfiy45hNWUUn1af3IBva7yOEP0iKZr1D+m8XOBAZp1Bn+7/UIttHWprSMABHnEhy9AplbMlUY0A2vdClTv8MjfMAoKEGXW2N2ZrFy5598rwJJN/6cMrMQOVM0SBCpBHu6Vm0N1FrIEsukRi3Ijue5/krgNUk9nyvqMC9fpGuVA==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg0oOuZVdeNchcC5cuia0J0FkQmCgim4/9C8YfzYlWYDomLmBzkMm66V7IhoNk9KVA+gJJXwIXWLqVOkL1d6baRMZTQEWHB5xzozetqTa5FOEf37w1UzPVutLXImK1Blg180eoBgvQq7YKjiYTkw9XIk4pu6X3XENb9zMR9oghjr4lKhcDsu1OHAhHOeq0ftSmj4w83D19bsWKSCIwVZncpUfuLgMR+vzBl7XJBn9eAkDxZs3Dyx0nlpATsD3jZnhUh/DvH0x8CZc12h3Tned52GO5f+H78EwdKgOm3IJHsjMIgX+FwfPtAplYHzAr8LAgA1FYq9X0Z+YPn+yDxwApQIDAQAB
  # 用于支付回调的url
  notifyUrl:  http://f3xnk7.natappfree.cc/pay/callback



# 开启 MyBatis Plus SQL 打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.baomidou.mybatisplus.core: debug

# 封禁功能布隆过滤器相关配置
ban:
  # 布隆过滤器大小，单位bit
  bloomFilterSize: 1024