server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/EasyBuy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

jwt:
  secret-key-str: huHAQ21P5fsGgpnHKipREwz4zgwUxJ8bGl+gmW4mbl4=
  # token 有效期 单位：天
  ttl: 99

mybatis:
  mapper-locations: classpath:mapper/*.xml